### ISSUE TITLE
一点建议

### ISSUE THREAD

**Issue by HaiTeng-Wang** [iOS-Tips/iOS-tech-set#12]
这帮人整些没什么软用的东西。还以为好伟大。“知识小集”点子不错，初衷不错，内容太一般。

**Comment by southpeak** [comment]
@HaiTeng-Wang 大神，您请出门左转，我们的内容不适合您，达不到您的要求。不好意思，我们的内容更多的是针对广大的开发人员，不是您这种大神。麻烦您该拉黑的拉黑，该取关的取关，谢谢！！！

**Comment by Damonvvong** [comment]
@HaiTeng-Wang 
问题是，吃你家大米了，还是影响你出名了？来这找啥存在感？
别用整这些没用的话，要觉得内容一般，你搞一些内容牛逼的出来再来这BB。
真以为自己天下第一的了

**Comment by HaiTeng-Wang** [comment]
弱弱的客观说一下心里话，给我这个小黑粉喷到无地自容。出门左转了，拜拜。不要全网封杀我。大神威武。
